### ISSUE TITLE
Distribute Workflow: self-referenced entities

### ISSUE THREAD

**Issue by tcorcor1** [AndrewButenko/UltimateWorkflowToolkit#24]
When using "distribute workflow" activity on self-referenced entities (i.e. parent > child account) I received the following error:

Entity role must be specified for reflexive relationship 'account_parent_account.'

**Comment by gprof** [comment]
@AndrewButenko - I am having this error also on a custom self referencing entity (parent - child). I tried both Distribute Workflow and Distribute Action. Is this is known issue or is there a trick to get this to work? Any suggestions would be appreciated.

**Comment by AndrewButenko** [comment]
Hello,
Yeah, It's a gap in my toolkit but luckily there is a workaround. First - build fetchxml that will return you the list of records you want to use in self-reference relationship and instead of using pair "Record Reference" and relationship - use FetchXml that is available in both Distribute Workflow and Distribute action. Feel free to update the thread if it's not totally clear what I meant.
Thanks for using UWT!
Andrew

**Comment by gprof** [comment]
@AndrewButenko - thanks for confirming. Do you have an example of how to create and use fetchXML in Distribute WF or Action and how to pass the GUID of the parent record? Thanks for all your work on the UWT - I use it a lot !

**Comment by yleclerc** [comment]
Hi Andrew,

I ran into the same problem as tcorcor1. So I followed your advice.

1. Empty the field called Record
2. Empty the field called Relationship Name

Then I built a fetchxml that returns the list of records I want and put the XML in FetchXml Query field. But then the workflow runs on all records that fits with that query. What if I want to run this only on the selected record?

I want to run ths workflow on child accounts for the selected account. So I use a rollup field to make sure the account has at least one child account. Here is my FetchXml:

```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="account">
    <order attribute="name" descending="false" />
    <filter type="and">
      <condition attribute="new_childaccount_count" operator="gt" value="0" />
    </filter>
  </entity>
</fetch>
```

What am I missing?

Thanks!

**Comment by AndrewButenko** [comment]
Yvan, include filtering by your record to FetchXml. In order to use recordid you can use "System: Get Record Details" step.

**Comment by yleclerc** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️

My bad! Thanks for your help!

I could not find _System: Get Record Details_ so I used _Core Operations:Any: Get Record Id_ instead.

If this can help others, I referenced the Parent record in the FextchXml with the Under Operator to distribute to Child accounts. Something like this:

```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="account">
    <order attribute="name" descending="false" />
    <filter type="and">
      <condition attribute="accountid" operator="under" uiname="xxxxxx" uitype="account" value="{xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" />
    </filter>
  </entity>
</fetch>
```
